services:
  cafe_server:
    container_name: cafe_server
    image: 'roisfaozi/caffe-server-collab:1'
    ports:
      - '8081:8081'
    networks:
      - coffee_net
    environment:
      - DB_HOST=ep-rough-frost-a1hlex1a.ap-southeast-1.aws.neon.tech
      - DB_NAME=black-coffee
      - DB_USER=black-coffee_owner
      - DB_PASS=qcfTuJ1xYhi5
      - JWT_SECRET="7fefaa467dd5adc78771223fdad980e8d4c6a72fdea8aaa4f01eae5ed6f8acc3"
    restart: always


volumes:
  postgres_data:

networks:
  coffee_net:
    name: coffee_net
    driver: bridge